#exec-once = uwsm-app dropbox
#exec-once = glance --config ~/.config/glance/config.yaml
exec-once = systemctl --user start hyprpolkitagent
#exec = pgrep -x "hypridle" > /dev/null || hypridle
#exec-once = swww-daemon
#exec-once = swww img /home/heinz/Imagens/wallpapers/default.png
exec-once = waybar
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = copyq --start-server 
exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = mpvpaper -o "loop-file=inf no-audio" "*" ~/Imagens/LIVE\ WALLPAPERS/2b.mp4