# Selection Colors
selection_foreground     #ebdbb2
selection_background     #d65d0e

# Window border Colors
active_border_color      #8ec07c
inactive_border_color    #665c54

# Kitty tabs colors 
active_tab_foreground    #ebdbb2
active_tab_background    #458588
inactive_tab_foreground  #ebdbb2
inactive_tab_background  #8ec07c

# Basic color
background               #1d1f21
foreground               #8b8d8d

# black
color0 #45475A
color8 #585B70

# red
color1 #F38BA8
color9 #F38BA8

# green
color2  #A6E3A1
color10 #A6E3A1

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #89B4FA
color12 #89B4FA

# magenta
color5  #F5C2E7
color13 #F5C2E7

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8
# Cursor colors
cursor                   #bdae93
cursor_text_color        #665c54

# Url color
url_color                #458588
