# env = GTK_THEME,AxMat
exec = hyprctl setcursor "Simp1e-Mix-Dark" 24
source = ~/.config/hypr/source/colors.conf


exec = hyprctl setcursor "Bibata-Modern-Classic" 24

decoration {
    blur {
        enabled = yes
        size = 5
        passes = 3
        new_optimizations = yes
        contrast = 1
        brightness = 1
    }
    rounding = 15

    shadow {
      enabled = true
      range = 10
      render_power = 2
      color = rgba(0, 0, 0, 0.25)
    }
}

general {
      gaps_in = 5
      gaps_out = 20
      border_size = 2
      col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
      col.inactive_border = rgba(595959aa)
      layout = dwindle
 }

animations {
    enabled = 1
    bezier    = overshot, 0.13, 0.99, 0.29, 1.1 
    animation = windows, 1, 7, overshot, slide 
    animation = windowsIn, 1, 7, overshot, slide 
    animation = windowsOut, 1, 7, overshot, slide 
    animation = windowsMove, 1, 7, overshot, slide 
    animation = border, 1, 8, default
    animation = fade, 1, 8, overshot,

}
